name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - run: pip install -r py-marktest

      - run: python -m py-marktest blog.md
      
      - uses: actions/upload-artifact@v3
        with:
          path: ./_testfile.py
          retention-days: 7
